#!/bin/bash
if [ -z "$2" ]
then
  echo "Usage: $0 [domain] [examples_file]" 1>&2
  exit 1
fi

cp evaluator/sempre/module-classes.txt .

java -ea -Dmodules=core,freebase,overnight \
  -Xms12G -Xmx32G \
  -cp evaluator/sempre/libsempre/*:evaluator/sempre/lib/* \
  edu.stanford.nlp.sempre.overnight.ExecuteLogicalForms \
  -JavaExecutor.convertNumberValues false \
  -executor JavaExecutor \
  -SimpleWorld.domain ${1} \
  -SimpleWorld.dbPath "lib/data/overnight/dbs/scholar.bootstrapped.db" \
  -Dataset.splitDevFromTrain 0 \
  -Grammar.tags generate general \
  -ExecuteLogicalForms.inPath ${2}
